version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=secret_key
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=test_db
      - DB_USER=test_db_user
      - DB_PASSWORD=test_db_password
      - CELERY_BROKER_URL=redis://:redispass@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:redispass@redis:6379/1
      - CACHE_LOCATION=redis://:redispass@redis:6379/2
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_db_user
      - POSTGRES_PASSWORD=test_db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d test_db -U test_db_user"]
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispass
    volumes:
      - dev-redis-data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025 
    depends_on:
      db:
        condition: service_healthy

  celery:
    build:
      context: .
    command: >
      sh -c "sleep 5 &&
             celery -A app worker --loglevel=info"
    environment:
      - SECRET_KEY=secret_key
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=test_db
      - DB_USER=test_db_user
      - DB_PASSWORD=test_db_password
      - CELERY_BROKER_URL=redis://:redispass@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:redispass@redis:6379/1
      - CACHE_LOCATION=redis://:redispass@redis:6379/2
    volumes:
       - ./app:/app
    depends_on:
      - app

volumes:
  dev-db-data:
  dev-static-data:
  dev-redis-data: